### ISSUE TITLE
Call 'split' for nil value

### ISSUE THREAD

**Issue by damanis** [crusj/bookmarks.nvim#1]
**How to reproduce**
- git clone of the plugin
- add default configuration (from README)
- open any file in nvim (terminal or GUI)
- add two bookmarks by `'\\z'`
- open bookmarks list by `<tab><tab>`

![image](https://user-images.githubusercontent.com/65733488/186588370-685afba8-cbf2-4661-b993-0d24b87383b7.png)

**Comment by crusj** [comment]
> **How to reproduce**
> 
> * git clone of the plugin
> * add default configuration (from README)
> * open any file in nvim (terminal or GUI)
> * add two bookmarks by `'\\z'`
> * open bookmarks list by `<tab><tab>`
> 
> ![image](https://user-images.githubusercontent.com/65733488/186588370-685afba8-cbf2-4661-b993-0d24b87383b7.png)

I ssh to a Linux server and tried it once.
* change dir  .local/share/nvim/site/pack/packer/start
* git clone https://github.com/crusj/bookmarks.nvim
* copy default config into ~/.config/nvim/init.lua
* add bookmark(\\z)
* open(tab,tab)

It is ok! 
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/20185895/186595771-20480940-07df-4312-9d92-edcd58b24f28.png">

**Comment by damanis** [comment]
Interesting. I tried just 'require("bookmarks").setup{}' with same error.
Do you know compatibility problem with other modules?
nvim version - today's nightly

**Comment by crusj** [comment]
> Interesting. I tried just 'require("bookmarks").setup{}' with same error. Do you know compatibility problem with other modules? nvim version - today's nightly

I'm using nvim 0.7.2, I'll try nightly later.
I think this plugin does not conflict with others.

**Comment by damanis** [comment]
I got same problem with nvim 0.7.2

**Comment by crusj** [comment]
> I got same problem with nvim 0.7.2

Can you use another host or block other plugins to try? this error seems to be because the filename is a nil value when splitting , I try it in the mac multi-plugin environment and Linux is ok

**Comment by damanis** [comment]
I disabled all others plugins - same error.

**Comment by crusj** [comment]
Can you help me debug to see what prints:
Add some code to the plugin's list.lua line 29 when you add bookmark \\z
<img width="751" alt="image" src="https://user-images.githubusercontent.com/20185895/186791941-59a7340b-8762-49de-850e-9ab485d00e0a.png">

Add some code to the list.lua line 74 when you open bookmarks window <tab><tab>
<img width="582" alt="image" src="https://user-images.githubusercontent.com/20185895/186792309-f19743eb-3ef6-41de-8312-48f3676a258e.png">

**Comment by crusj** [comment]
> I got same problem with nvim 0.7.2

Can you help me debug to see what prints:
Add some code to the plugin's list.lua line 29 when you add bookmark \\z
<img width="751" alt="image" src="https://user-images.githubusercontent.com/20185895/186791941-59a7340b-8762-49de-850e-9ab485d00e0a.png">

Add some code to the list.lua line 74 when you open bookmarks window <tab><tab>
<img width="582" alt="image" src="https://user-images.githubusercontent.com/20185895/186792309-f19743eb-3ef6-41de-8312-48f3676a258e.png">

**Comment by damanis** [comment]
I'll do next week.

**Comment by damanis** [comment]
Tested on another VM with Ubuntu 22.
I opened ~/.bashrc, added two bookmark, test1 and test2, then press <tab><tab>
![изображение](https://user-images.githubusercontent.com/65733488/186962993-0b542d31-8bd8-42fd-a349-d4f5e6250843.png)

**Comment by crusj** [comment]
> Tested on another VM with Ubuntu 22. I opened ~/.bashrc, added two bookmark, test1 and test2, then press ![изображение](https://user-images.githubusercontent.com/65733488/186962993-0b542d31-8bd8-42fd-a349-d4f5e6250843.png)

I found the problem because I extended string, thanks for your help.

**Comment by crusj** [comment]
> Tested on another VM with Ubuntu 22. I opened ~/.bashrc, added two bookmark, test1 and test2, then press ![изображение](https://user-images.githubusercontent.com/65733488/186962993-0b542d31-8bd8-42fd-a349-d4f5e6250843.png)

I have fixed the problem.

**Comment by damanis** [comment]
Great! Thank you.
