### ISSUE TITLE
Any plans to integrate this with telescope?

### ISSUE THREAD

**Issue by dpkpnm** [crusj/bookmarks.nvim#14]
Plugin is great any plans to integrate it with telescope for easy search.

**Comment by lytex** [comment]
A good starting point could be this telescope extension of another bookmark extension:

https://github.com/tom-anders/telescope-vim-bookmarks.nvim

_In theory_ it's just keeping the same structure, and replacing functions calls from one bookmark extension to another

**Comment by crusj** [comment]
I will.

**Comment by crusj** [comment]
I have initially integrated telescope, you can use the git  branch `integrate-with-telescope`  for trial and feedback.
`require("telescope").load_extension("bookmarks") `
@dpkpnm @lytex
