### ISSUE TITLE
Signs in signcolum option

### ISSUE THREAD

**Issue by ttytm** [crusj/bookmarks.nvim#16]
Thanks for the work, the plugin is awesome!

If it's not too much hassle, I'd love to have an option to display bookmark sings in the singcolumn.

![Screenshot_20230409_142744](https://user-images.githubusercontent.com/34311583/230772701-6e39336c-b528-403e-8ff3-ed9b08ba6ed1.png)

If a PR is of any help, I have some time next month to submit something.

**Comment by crusj** [comment]
> Thanks for the work, the plugin is awesome!
> 
> If it's not too much hassle, I'd love to have an option to display bookmark sings in the singcolumn.
> 
> ![Screenshot_20230409_142744](https://user-images.githubusercontent.com/34311583/230772701-6e39336c-b528-403e-8ff3-ed9b08ba6ed1.png)
> 
> If a PR is of any help, I have some time next month to submit something.

I added this feature that I think is useful.

**Comment by crusj** [comment]
<img width="859" alt="image" src="https://github.com/crusj/bookmarks.nvim/assets/20185895/a1460d14-269b-4c2b-a451-7f97839ff277">

**Comment by crusj** [comment]
Done

**Comment by crusj** [comment]
Done
