### ISSUE TITLE
Highlight groups for bookmark window

### ISSUE THREAD

**Issue by ttytm** [crusj/bookmarks.nvim#17]
It would be great to have the possibility to highlight the bookmark preview window and define border styles. For me it would provide consistent border style with the rest of the config.

E.g. in terms of highlights, the bookmarks window could use the `"FloatBorder"` and `"FloatTitle"` highlights.

Styles could be common predefined styles(`"single"`, `"rounded"`, `"dobule"`) or/and a custom set of characters. 

![Screenshot_20230409_143231](https://user-images.githubusercontent.com/34311583/230773038-6f17f1dd-e592-4514-af6a-aa4afd1d0eec.png)

![Screenshot_20230409_143239](https://user-images.githubusercontent.com/34311583/230773158-a47d2e23-5583-497e-85b6-680fb31a321b.png)

Let me know if a PR would be of any help :+1:

**Comment by crusj** [comment]
> It would be great to have the possibility to highlight the bookmark preview window and define border styles. For me it would provide consistent border style with the rest of the config.
> 
> E.g. in terms of highlights, the bookmarks window could use the `"FloatBorder"` and `"FloatTitle"` highlights.
> 
> Styles could be common predefined styles(`"single"`, `"rounded"`, `"dobule"`) or/and a custom set of characters.
> 
> ![Screenshot_20230409_143231](https://user-images.githubusercontent.com/34311583/230773038-6f17f1dd-e592-4514-af6a-aa4afd1d0eec.png)
> 
> ![Screenshot_20230409_143239](https://user-images.githubusercontent.com/34311583/230773158-a47d2e23-5583-497e-85b6-680fb31a321b.png)
> 
> Let me know if a PR would be of any help +1

I have made an update.

**Comment by ttytm** [comment]
Very nice thanks alot @crusj !
