### ISSUE TITLE
Syntax highlighting / Set filetype for previewed file in bookmarks float window

### ISSUE THREAD

**Issue by ttytm** [crusj/bookmarks.nvim#18]
Currently, no filetype is set for a previewed filed. Setting the ft would enable syntax highlighting.

I didn't made any implementation test yet, so my theoretical assumptionion on how this could be solved: It might be possible to directly retrieve the filetype when opening the  preview. If not, it might be worth the tradeoff to additionally save `ft = vim.bo.ft` on bookmark creation.

Screenshot, manually setting the ft in a previewed file after opening the window.

![Screenshot_20230410_114726](https://user-images.githubusercontent.com/34311583/230880307-e31d7fd8-1101-4a4f-8ee0-043df72ba9da.png)

Might be related to #13 (edit: didn't read through the issue properly. No relation afaik.)

**Comment by crusj** [comment]
> Currently, no filetype is set for a previewed filed. Setting the ft would enable syntax highlighting.
> 
> I didn't made any implementation test yet, so my theoretical assumptionion on how this could be solved: It might be possible to directly retrieve the filetype when opening the preview. If not, it might be worth the tradeoff to additionally save `ft = vim.bo.ft` on bookmark creation.
> 
> Screenshot, manually setting the ft in a previewed file after opening the window.
> 
> ![Screenshot_20230410_114726](https://user-images.githubusercontent.com/34311583/230880307-e31d7fd8-1101-4a4f-8ee0-043df72ba9da.png)
> 
> Might be related to #13 (edit: didn't read through the issue properly. No relation afaik.)

In the setup options, `preview_ext_enable` is used to configure whether to add a filetype suffix to the current buffer.

**Comment by ttytm** [comment]
Awesome! Sorry for not checking better beforehand. 
Let me close this.
