### ISSUE TITLE
Incorrect bookmark position after file changed

### ISSUE THREAD

**Issue by damanis** [crusj/bookmarks.nvim#2]
Feature propose.
- add bookmark to some line
- add several lines before the bookmarked line
- jump to bookmark - jump to incorrect line
The [simple bookmark plugin](https://github.com/AndrewRadev/simple_bookmarks.vim) may be used as reference.

**Comment by crusj** [comment]
> Feature propose.
> 
> * add bookmark to some line
> * add several lines before the bookmarked line
> * jump to bookmark - jump to incorrect line
>   The [simple bookmark plugin](https://github.com/AndrewRadev/simple_bookmarks.vim) may be used as reference.

Jumping to an incorrect line is because the bookmark records the line number of the file. When the file changes, if the line number corresponding to the bookmark changes, the jump will be incorrect. I tried the plugin AndrewRadev/simple_bookmarks.vim also jumps to the incorrect line when the file changes, I didn't think of a better way to fix this.

**Comment by damanis** [comment]
You right.

**Comment by crusj** [comment]
> You right.

But I'm currently trying to fix the bookmark line number as best I can in some way when the file changes.

**Comment by crusj** [comment]
> You right.

You could try the dev branch, which tries to fix bookmarked line numbers when the file changes.

**Comment by damanis** [comment]
'dev' branch drops errors:

![image](https://user-images.githubusercontent.com/65733488/187164250-869935f2-56ca-48f0-a268-b0745b0b96b2.png)

**Comment by crusj** [comment]
> 'dev' branch drops errors:
> 
> ![image](https://user-images.githubusercontent.com/65733488/187164250-869935f2-56ca-48f0-a268-b0745b0b96b2.png)

You should install lua language and configure it in environment variables

**Comment by damanis** [comment]
It works if line itself was not changed (e.g., spaces added).
You added event for BufWritePost, so it will not work after git update.
Anyway, now I'm not sure the feature is useful.

There is side effect in 'write' command:
![image](https://user-images.githubusercontent.com/65733488/187170313-9fbcc9e7-aed2-4b55-8a70-fdb7be55cb14.png)

**Comment by crusj** [comment]
> It works if line itself was not changed (e.g., spaces added). You added event for BufWritePost, so it will not work after git update. Anyway, now I'm not sure the feature is useful.
> 
> There is side effect in 'write' command: ![image](https://user-images.githubusercontent.com/65733488/187170313-9fbcc9e7-aed2-4b55-8a70-fdb7be55cb14.png)

I am indeed adding a buffer write event, and doing a content comparison and changing the line number, if git updates really no way, but at least try to fix

**Comment by pidgeon777** [comment]
Just wondering if this has been fixed: if the buffer externally changes, the plugin keeps that into account, updating the corresponding bookmarked lines.
