### ISSUE TITLE
How to customize the storage path?

### ISSUE THREAD

**Issue by Xiaobo2020** [crusj/bookmarks.nvim#22]
As mentioned in the title, I want to set the location where the bookmark information is stored, instead of the default `.local/share/nvim/bookmarks`

**Comment by crusj** [comment]
> As mentioned in the title, I want to set the location where the bookmark information is stored, instead of the default `.local/share/nvim/bookmarks`


Well, I will add a configuration option.

**Comment by crusj** [comment]
Done!

**Comment by Xiaobo2020** [comment]
Hey @crusj. Great to hear about the new storage_dir field. I tried setting the storage path to `~/.config/storage/nvim/bookmarks` locally via `storage_dir`, but that didn't seem to work.

```
require("bookmarks").setup({
  storage_dir: "~/.config/storage/nvim/bookmarks",
  // ...
})
```

**Comment by crusj** [comment]
> Hey @crusj. Great to hear about the new storage_dir field. I tried setting the storage path to `~/.config/storage/nvim/bookmarks` locally via `storage_dir`, but that didn't seem to work.
> 
> ```
> require("bookmarks").setup({
>   storage_dir: "~/.config/storage/nvim/bookmarks",
>   // ...
> })
> ```

You should use absolute path.
