### ISSUE TITLE
Filetype detection in preview windows

### ISSUE THREAD

**Issue by jthvai** [crusj/bookmarks.nvim#23]
Related to #18.

In [window.lua](https://github.com/crusj/bookmarks.nvim/blob/main/lua/bookmarks/window.lua#L180), it's assumed that the file extension is a valid treesitter filetype (for syntax highlighting) - which doesn't hold.

Consequently, if `preview_ext_enable = true` and the file with bookmarks doesn't have an extension, the following error occurs upon spawning the bookmarks window, as well as scrolling to different items (`J` or `K`), deleting bookmarks (`dd`), (non-exhaustive list) once every time.

```txt
Error detected while processing CursorMoved Autocommands for "<buffer=10>":
Error executing lua callback: ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:180: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:180: in function 'preview_bookmark'
        ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:32: in function <...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:17>
```

Also, if the extension doesn't match the treesitter filetype (e.g. with `py` and `python`), the preview window won't be highlighted (though I think you've already accounted for this).

I'm not sure what the best way to go about this would be; quoting @tobealive from #18,

> [...] it might be worth the tradeoff to additionally save `ft = vim.bo.ft` on bookmark creation

is an interesting idea. Or, [the way neo-tree have done previews](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/common/preview.lua#L299) might be interesting - I don't notice a performance loss there personally.

I wish I could offer more information or help, but I'm fairly new to lua 😅

**Comment by crusj** [comment]
> Related to #18.
> 
> In [window.lua](https://github.com/crusj/bookmarks.nvim/blob/main/lua/bookmarks/window.lua#L180), it's assumed that the file extension is a valid treesitter filetype (for syntax highlighting) - which doesn't hold.
> 
> Consequently, if `preview_ext_enable = true` and the file with bookmarks doesn't have an extension, the following error occurs upon spawning the bookmarks window, as well as scrolling to different items (`J` or `K`), deleting bookmarks (`dd`), (non-exhaustive list) once every time.
> 
> ```
> Error detected while processing CursorMoved Autocommands for "<buffer=10>":
> Error executing lua callback: ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:180: E474: Invalid argument
> stack traceback:
>         [C]: in function 'nvim_buf_set_option'
>         ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:180: in function 'preview_bookmark'
>         ...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:32: in function <...local/share/nvim/lazy/bookmarks/lua/bookmarks/window.lua:17>
> ```
> 
> Also, if the extension doesn't match the treesitter filetype (e.g. with `py` and `python`), the preview window won't be highlighted (though I think you've already accounted for this).
> 
> I'm not sure what the best way to go about this would be; quoting @tobealive from #18,
> 
> > [...] it might be worth the tradeoff to additionally save `ft = vim.bo.ft` on bookmark creation
> 
> is an interesting idea. Or, [the way neo-tree have done previews](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/common/preview.lua#L299) might be interesting - I don't notice a performance loss there personally.
> 
> I wish I could offer more information or help, but I'm fairly new to lua 😅

I found that when the filename does not have an extension, an error occurs if the preview__ext_enable is set, I have fixed it, please update the plugin.
