### ISSUE TITLE
Feature request: Replace virt_pattern by disabled file types

### ISSUE THREAD

**Issue by MariaSolOs** [crusj/bookmarks.nvim#24]
From my use of other plugins, I find it more intuitive to indicate which file types I don't want the virtual mark to be enabled in, rather than having to list all the extensions I want the virtual mark to appear in.

**Comment by crusj** [comment]
> From my use of other plugins, I find it more intuitive to indicate which file types I don't want the virtual mark to be enabled in, rather than having to list all the extensions I want the virtual mark to appear in.

If it did, it would be a completely opposite change, I would consider it.

**Comment by MariaSolOs** [comment]
@crusj maybe you could add an opposite setting and require at most one to be defined. That is, have an `ignore_virt_pattern` setting which cannot be defined at the same time as `virt_pattern`.

**Comment by crusj** [comment]
The issue will be closed.

**Comment by sshelll** [comment]
#43 @MariaSolOs @crusj Hi guys~ I've done this feature in this PR, this works on my local env~
