### ISSUE TITLE
Possible bug concerning config item virt_pattern

### ISSUE THREAD

**Issue by lgeralds** [crusj/bookmarks.nvim#26]
virt_pattern is limited to five items. In the file bookmarks.nvim/lua/bookmarks/config.lua, tables are being copied item by item. This makes sense for keymap and hl. They have defined membership.

virt_pattern is open ended.

Changing line bookmarks.nvim/lua/bookmarks/config.lua#35 to:
`` if type(dv) ~= "table" or dk == 'virt_pattern' then``
copies all items.

**Comment by crusj** [comment]
> virt_pattern is limited to five items. In the file bookmarks.nvim/lua/bookmarks/config.lua, tables are being copied item by item. This makes sense for keymap and hl. They have defined membership.
> 
> virt_pattern is open ended.
> 
> Changing line bookmarks.nvim/lua/bookmarks/config.lua#35 to: ` if type(dv) ~= "table" or dk == 'virt_pattern' then` copies all items.

Thank you. You're right.
