### ISSUE TITLE
Display bookmark description as virtual text

### ISSUE THREAD

**Issue by lawrence-laz** [crusj/bookmarks.nvim#29]
Is there a way to always display bookmark's description as virtual text?

**Comment by crusj** [comment]
> Is there a way to always display bookmark's description as virtual text?

Not currently, I can add this feature.

**Comment by crusj** [comment]
> Is there a way to always display bookmark's description as virtual text?

You can set the configuration option `virt_text` to an empty string.

**Comment by lawrence-laz** [comment]
Yes, this is what I needed. Although, now I cannot modify the bookmark icon. I used to have it like this:
<img width="240" alt="image" src="https://github.com/crusj/bookmarks.nvim/assets/8823448/8eb96da7-42cb-4678-b239-5f9817d65875">

**Comment by crusj** [comment]
> Yes, this is what I needed. Although, now I cannot modify the bookmark icon. I used to have it like this: <img alt="image" width="240" src="https://user-images.githubusercontent.com/8823448/274990734-8eb96da7-42cb-4678-b239-5f9817d65875.png">

I added a default icon,I'll update the code configuration options for this.

**Comment by crusj** [comment]
Now set virt_text to an empty string, it only shows the description. If you want to add ICONN, you can fork and simply modify the code.
`bookmarks/mark.lua 45`
<img width="363" alt="image" src="https://github.com/crusj/bookmarks.nvim/assets/20185895/fee3a547-8856-4842-8f93-77767ac8af95">

**Comment by crusj** [comment]
<img width="804" alt="image" src="https://github.com/crusj/bookmarks.nvim/assets/20185895/c8261ace-9467-4724-aad9-b86884090fe5">
The configuration item has added sign_icon, which is probably better.

**Comment by lawrence-laz** [comment]
Very nice! Thank you
