### ISSUE TITLE
tabline for bookmarks with hotkeys to go to it

### ISSUE THREAD

**Issue by otavioschwanck** [crusj/bookmarks.nvim#30]
Would be awesome to have a tabline like from harpoon:

![image](https://github.com/crusj/bookmarks.nvim/assets/9551316/7c1d29a1-85a9-4333-a067-983adcdcf5a1)

It would help to quick switch to bookmarks (could define shortcuts to go to first/second/etc.

**Comment by crusj** [comment]
> Would be awesome to have a tabline like from harpoon:
Why tabline?
You can normally use any vim jump shortcut in the bookmark list, such as gg, G, 3G.

**Comment by crusj** [comment]
> Would be awesome to have a tabline like from harpoon:
> 
> ![image](https://user-images.githubusercontent.com/9551316/274986964-7c1d29a1-85a9-4333-a067-983adcdcf5a1.png)
> 
> It would help to quick switch to bookmarks (could define shortcuts to go to first/second/etc.

Why tabline?
You can normally use any vim jump shortcut in the bookmark list, such as gg, G, 3G.

**Comment by otavioschwanck** [comment]
> > Would be awesome to have a tabline like from harpoon:
> > ![image](https://user-images.githubusercontent.com/9551316/274986964-7c1d29a1-85a9-4333-a067-983adcdcf5a1.png)
> > It would help to quick switch to bookmarks (could define shortcuts to go to first/second/etc.
> 
> Why tabline? You can normally use any vim jump shortcut in the bookmark list, such as gg, G, 3G.

1. i could see the bookmarks without entering in the UI
2. i could switch to the bookmarks without entering in the UI

**Comment by crusj** [comment]
> > > Would be awesome to have a tabline like from harpoon:
> > > ![image](https://user-images.githubusercontent.com/9551316/274986964-7c1d29a1-85a9-4333-a067-983adcdcf5a1.png)
> > > It would help to quick switch to bookmarks (could define shortcuts to go to first/second/etc.
> > 
> > 
> > Why tabline? You can normally use any vim jump shortcut in the bookmark list, such as gg, G, 3G.
> 
> 1. i could see the bookmarks without entering in the UI
> 2. i could switch to the bookmarks without entering in the UI
I think you're looking for a Marks plugin.


> > > Would be awesome to have a tabline like from harpoon:
> > > ![image](https://user-images.githubusercontent.com/9551316/274986964-7c1d29a1-85a9-4333-a067-983adcdcf5a1.png)
> > > It would help to quick switch to bookmarks (could define shortcuts to go to first/second/etc.
> > 
> > 
> > Why tabline? You can normally use any vim jump shortcut in the bookmark list, such as gg, G, 3G.
> 
> 1. i could see the bookmarks without entering in the UI
> 2. i could switch to the bookmarks without entering in the UI

I think you're looking for a Marks plugin.
