### ISSUE TITLE
bookmarks data split by cwd may not be a good choice I think?

### ISSUE THREAD

**Issue by onns** [crusj/bookmarks.nvim#31]
Thanks for developing such a good plugin, I wanna use bookmarks because I need to read a large project, understand how data transfer from one method to another, maybe many files in different folders. Saving bookmarks to different pwd makes hard to search.
For me, I use coc.vim to auto complete so, it has `vim.g.WorkspaceFolders` to help me locate the root path of my project. Also, `nvim.fn.find_root_directory(start_directory, marker_file)` can help us find the root path without lsp, they are similar by the way.

```
 local root_directory = nvim.fn.find_root_directory(cwd, ".git")
```

Maybe this is better for searching?

**Comment by crusj** [comment]
> Thanks for developing such a good plugin, I wanna use bookmarks because I need to read a large project, understand how data transfer from one method to another, maybe many files in different folders. Saving bookmarks to different pwd makes hard to search. For me, I use coc.vim to auto complete so, it has `vim.g.WorkspaceFolders` to help me locate the root path of my project. Also, `nvim.fn.find_root_directory(start_directory, marker_file)` can help us find the root path without lsp, they are similar by the way.
> 
> ```
>  local root_directory = nvim.fn.find_root_directory(cwd, ".git")
> ```
> 
> Maybe this is better for searching?

No matter how big your project is or how many files there are, you only need to open nvim in the root folder of the project to save and access all bookmarks in the project, including subfolders and subfiles, if you access the bookmarks of the B project in A project, it is not yet implemented.

**Comment by onns** [comment]
I agree with you at the first time I install the plug-in, but, after I bookmark some files in my project(multi files in one project), quit neovim and reopen it(from root path of the project, like what you say), bookmarks disappear.

And from that time I began to find the reason, I found bookmarks are saved via cwd, but in my project, every time I change buffer to a new file from a new folder, the result of cwd changes too. (Test by print(vim.fn.getcmd()) under command model)

I was new to lua config so I don’t know if this only happens to me.

**Comment by crusj** [comment]
> I agree with you at the first time I install the plug-in, but, after I bookmark some files in my project(multi files in one project), quit neovim and reopen it(from root path of the project, like what you say), bookmarks disappear. And from that time I began to find the reason, I found bookmarks are saved via cwd, but in my project, every time I change buffer to a new file from a new folder, the result of cwd changes too. (Test by print(vim.fn.getcmd()) under command model) I was new to lua config so I don’t know if this only happens to me.

I'm using the `getcwd` function, which returns the working directory, which is where nvim started, and should not change.

**Comment by onns** [comment]
![图片](https://github.com/crusj/bookmarks.nvim/assets/16622934/ded9e1f2-b3ff-485c-992a-e21de957775a)
![图片](https://github.com/crusj/bookmarks.nvim/assets/16622934/f7763bf6-5528-41a6-925e-84b2a4eaf61b)
![图片](https://github.com/crusj/bookmarks.nvim/assets/16622934/cf99dad3-c846-4a16-9dd2-9f8ba8c2b993)
![图片](https://github.com/crusj/bookmarks.nvim/assets/16622934/d85b4d21-a6fc-4b8d-abc3-1af41f80f36a)
not for me...

**Comment by onns** [comment]
I just begin to use lua config, start with [https://github.com/LazyVim/LazyVim](https://github.com/LazyVim/LazyVim), before that I use pure vim script config.(the reason is, I found it is hard to use bookmarks plugin by vim-script)

![图片](https://github.com/crusj/bookmarks.nvim/assets/16622934/fb4ad706-62c8-46e3-9fb6-73409e28d396)

so I don't know if this only happens to me

**Comment by crusj** [comment]
> ![图片](https://user-images.githubusercontent.com/16622934/276833144-ded9e1f2-b3ff-485c-992a-e21de957775a.png) ![图片](https://user-images.githubusercontent.com/16622934/276833195-f7763bf6-5528-41a6-925e-84b2a4eaf61b.png) ![图片](https://user-images.githubusercontent.com/16622934/276833246-cf99dad3-c846-4a16-9dd2-9f8ba8c2b993.png) ![图片](https://user-images.githubusercontent.com/16622934/276833283-d85b4d21-a6fc-4b8d-abc3-1af41f80f36a.png) not for me...

You can try loading only the bookmarks plugin to see if the same thing happens
