### ISSUE TITLE
is possible to skip input description when adding a new bookmark?

### ISSUE THREAD

**Issue by Martins3** [crusj/bookmarks.nvim#32]
Most of the time, through the preview of the telescope, users can already know the content marked by the bookmark, so wondering if an option can be added to skip the description.

**Comment by codezijie** [comment]
+1，I also hope fix this problem

**Comment by crusj** [comment]
The purpose of the description is to identify and search, if you skip it, you can't search in telescope.

**Comment by Martins3** [comment]
At least, we can search with the filename.

![image](https://github.com/crusj/bookmarks.nvim/assets/16731244/8b885e0c-d7a5-45cd-b3bd-3a29130233f6)
Actually, I only set a few tags in one project,  search is not so necessary for me. Maybe, we can make the tag optional, and it's default value is empty string.

I'll make a PR[^1] if the idea is acceptable.

[^1]: Currently, I am not very proficient in Lua programming, so it may take some time.

**Comment by crusj** [comment]
I guess you don't want to add a description because it's a bit cumbersome to enter a description, and you just want to use bookmark like a mark?

**Comment by Martins3** [comment]
> I guess you don't want to add a description because it's a bit cumbersome to enter a description, and you just want to use bookmark like a mark?↳

yes

**Comment by crusj** [comment]
> > I guess you don't want to add a description because it's a bit cumbersome to enter a description, and you just want to use bookmark like a mark?↳
> 
> yes

I don't want to do this, you can fork and make changes.

**Comment by Martins3** [comment]
Ok
