### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by drobban** [crusj/bookmarks.nvim#36]
Hi and big thanks for this plugin!

Im missing icons and I suspect its caused by missing fonts.

What fonts is bookmarks.nvim expect me to have installed?

**Comment by crusj** [comment]
Nerd font

> Hi and big thanks for this plugin!
> 
> Im missing icons and I suspect its caused by missing fonts.
> 
> What fonts is bookmarks.nvim expect me to have installed?

- Plugin: kyazdani42/nvim-web-devicons
- Font: Nerd font
