### ISSUE TITLE
Invalid escape sequence near ''C:'

### ISSUE THREAD

**Issue by calon** [crusj/bookmarks.nvim#37]
Environment:
neovim 0.9
Neovide GUI
Windows 11

After add bookmark, a file named "C" generated in the nvim-data/bookmarks folder, 0 byte size.
close nvim and open t again, the error pops.
the path of the file added to bookmark is some kind of "C:\path\file".
Guess the error refers to the path format on Windows OS.

**Comment by crusj** [comment]
Update plugin and delete all bookmarks data files.

**Comment by calon** [comment]
> Update plugin and delete all bookmarks data files.

Thanks!
