### ISSUE TITLE
Feature request: global bookmarks

### ISSUE THREAD

**Issue by yingzhu146** [crusj/bookmarks.nvim#38]
Apologies if this is available and I didn't RTFM correctly but would love if there was an option for global bookmarks that could be postpended to the local ones. I often need to jump to specific locations without wanting to switch workspaces (e.g. add a hotkey while working on another file). Global bookmarks (ideally enabled via separate hotkey) would be brilliant.

Thanks a ton for the amazing plugin!

**Comment by crusj** [comment]
> Apologies if this is available and I didn't RTFM correctly but would love if there was an option for global bookmarks that could be postpended to the local ones. I often need to jump to specific locations without wanting to switch workspaces (e.g. add a hotkey while working on another file). Global bookmarks (ideally enabled via separate hotkey) would be brilliant.
> 
> Thanks a ton for the amazing plugin!

Sorry for taking so long to update. You can pull the new version and try this feature.

**Comment by yingzhu146** [comment]
awesome thanks a lot! This is free work that I'm very grateful for, I had absolutely no expectation for this to be implemented so don't apologize! :) but am super excited it's available now
