### ISSUE TITLE
[Bug]Exiting nvim to reopen one of the bookmarks results in an error

### ISSUE THREAD

**Issue by DreamMaoMao** [crusj/bookmarks.nvim#39]
https://github.com/crusj/bookmarks.nvim/assets/30348075/354945e7-16c3-4b35-91c0-fb2efc1deab7

error message:
[error.log](https://github.com/crusj/bookmarks.nvim/files/13800943/error.log)

is seem that `data.bufp` will be nil when reopen neovim.
![image](https://github.com/crusj/bookmarks.nvim/assets/30348075/6351705b-f336-4a1d-b78c-31bb10c05908)

so I add a judgement,the error gone.
![image](https://github.com/crusj/bookmarks.nvim/assets/30348075/6cf98425-b3a7-4e3c-aaae-0b564d8bbfe3)

but it still has some problen, it will auto add a null split window and a empty buffer in neovim when reopen neovim:

https://github.com/crusj/bookmarks.nvim/assets/30348075/e7e6ac42-a592-46c9-9402-4c97af6539df

how to fixed it?

**Comment by DreamMaoMao** [comment]
The second problem has nothing to do with reopening it, it just happens when the current window doesn't have a buffer, and it's fine if you open bookmark after another file is opened.

https://github.com/crusj/bookmarks.nvim/assets/30348075/1179664a-89d6-4ca9-adbb-f7aac6bef1ca

**Comment by crusj** [comment]
> The second problem has nothing to do with reopening it, it just happens when the current window doesn't have a buffer, and it's fine if you open bookmark after another file is opened.
> 
>  2023-12-31.19-45-55.mp4

 You can use the  neotree. plug-in to open files and the same problem will occur.

**Comment by crusj** [comment]
> The second problem has nothing to do with reopening it, it just happens when the current window doesn't have a buffer, and it's fine if you open bookmark after another file is opened.
> 
>  2023-12-31.19-45-55.mp4

I revert commits and merge pr.

**Comment by DreamMaoMao** [comment]
thanks
