### ISSUE TITLE
Error message on adding bookmark

### ISSUE THREAD

**Issue by damanis** [crusj/bookmarks.nvim#4]
Reproduce:
- open js-file
- jump to line does not include 'require' word
- add bookmark - works properly
- jump to line with 'require'
- add bookmark - **error message, bookmark is not added**
Sometimes the error on line without 'require'

Screenshot: try add bookmark when cursor on line 'let qweqwe...'
![image](https://user-images.githubusercontent.com/65733488/189043448-c3167f5e-1f0e-4af3-9326-75d5234b0538.png)

**Comment by crusj** [comment]
> Reproduce:
> 
> * open js-file
> * jump to line does not include 'require' word
> * add bookmark - works properly
> * jump to line with 'require'
> * add bookmark - **error message, bookmark is not added**
>   Sometimes the error on line without 'require'
> 
> Screenshot: try add bookmark when cursor on line 'let qweqwe...' ![image](https://user-images.githubusercontent.com/65733488/189043448-c3167f5e-1f0e-4af3-9326-75d5234b0538.png)

fixed
