### ISSUE TITLE
Bookmark view toggle window does not respect window close event

### ISSUE THREAD

**Issue by mfiano** [crusj/bookmarks.nvim#5]
If you toggle the bookmarks view, and then issue `:close<cr>`. The cursor will return to the buffer under the floating window, but the floating window will remain. If you toggle the bookmarks view again, a new one is overlaid on top of the previous floating window, and toggling it closed will close itself, and *only the right side* of the original floating window.

I think this is counter-intuitive. Most libraries that use floating windows allow the window to be closed by normal means. The fact that the only way to close the floating window once you accidentally deviate from the toggle-to-close and use `:close`, is to restart neovim, should make this a high priority simple fix.

Thank you for the wonderful library by the way. I appreciate all your work!

**Comment by crusj** [comment]
> If you toggle the bookmarks view, and then issue `:close<cr>`. The cursor will return to the buffer under the floating window, but the floating window will remain. If you toggle the bookmarks view again, a new one is overlaid on top of the previous floating window, and toggling it closed will close itself, and _only the right side_ of the original floating window.
> 
> I think this is counter-intuitive. Most libraries that use floating windows allow the window to be closed by normal means. The fact that the only way to close the floating window once you accidentally deviate from the toggle-to-close and use `:close`, is to restart neovim, should make this a high priority simple fix.
> 
> Thank you for the wonderful library by the way. I appreciate all your work!

If you don't use the map toggle, it does have this problem, I didn't think about other ways to toggle it at the time, I will fix it.
