### ISSUE TITLE
[Feature] Set annotation to a bookmark and display it as virtual text

### ISSUE THREAD

**Issue by pidgeon777** [crusj/bookmarks.nvim#6]
It would be great to set a text (annotation) for a bookmark and display it as virtual text.

**Comment by crusj** [comment]
> It would be great to set a text (annotation) for a bookmark and display it as virtual text.

I'm worried that annotation will disturb areas of code.

**Comment by pidgeon777** [comment]
In my opinion, it could easily and visually greatly improved by using a technique like this:

https://github.com/Maan2003/lsp_lines.nvim

By doing that, we could have even a block of comments comfortably placed simply above or below the code of interest, maybe even by using different colours for comment highlights, thus improving readability a lot.

What do you think?

**Comment by crusj** [comment]
> 

I will consider it.

**Comment by pidgeon777** [comment]
Thank you, in my opinion, it would be a killer feature not available in any other plugin.

Something like:

- Set custom multiline virtual text for a given row/position (for code annotation etc.)
- Display the multiline virtual text under the corresponding row like done by `lsp_lines.nvim` (it even supports multiple positions in the same row).
- Display the virtual annotations with customizable different colours (for example red for critical, green for info, yellow for warning, etc.).
- Search for the text within those annotations (e.g. with Telescope) and jump to the corresponding buffer row.
- Import and export the notes.
- Option to display the virtual annotations all at once or dynamically (only when the cursor is placed over the corresponding code position).
- Git integration (to keep track of changed lines, commit authors, etc.).

Those are just ideas. It would be quite a new plugin, but it would implement killer features: one above all, no more need to add those annotations directly into the code as comments, which are subject to changes, thus making it also more readable.

**Comment by crusj** [comment]
> Thank you, in my opinion, it would be a killer feature not available in any other plugin.
> 
> Something like:
> 
> * Set custom multiline virtual text for a given row/position (for code annotation etc.)
> * Display the multiline virtual text under the corresponding row like done by `lsp_lines.nvim` (it even supports multiple positions in the same row).
> * Display the virtual annotations with customizable different colours (for example red for critical, green for info, yellow for warning, etc.).
> * Search for the text within those annotations (e.g. with Telescope) and jump to the corresponding buffer row.
> * Import and export the notes.
> * Option to display the virtual annotations all at once or dynamically (only when the cursor is placed over the corresponding code position).
> * Git integration (to keep track of changed lines, commit authors, etc.).
> 
> Those are just ideas. It would be quite a new plugin, but it would implement killer features: one above all, no more need to add those annotations directly into the code as comments, which are subject to changes, thus making it also more readable.

Good ideas.
